DROP DATABASE IF EXISTS testing;
CREATE DATABASE IF NOT EXISTS testing;
USE testing;

DROP TABLE IF EXISTS usuario;
CREATE TABLE IF NOT EXISTS usuario (
       id int NOT NULL,
       nombre varchar(30) NOT NULL,
       apellido varchar(35) NOT NULL,
       codpais varchar(3),
       PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO usuario (id, nombre,apellido,codpais) VALUES 
(1, 'Cesar','Chavez','MX'),
(2, 'Karla','Ricalde','AD'),
(3, 'Irving','Alvarez','AR'),
(4, 'Manuel','Chavez','MX'),
(5, 'Jonathan','Chavez','MX'),
(6, 'Cristian','Chavez','MX');

DROP TABLE IF EXISTS paises;
CREATE TABLE IF NOT EXISTS paises (
       codpais varchar(3) NOT NULL default '',
       pais varchar(30) default NULL,
       PRIMARY KEY  (codpais)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO paises (codpais, pais) VALUES 
('AD', 'Andorra'),
('AE', 'Emiratos Arabes Unidos'),
('AF', 'Afganistan'),
('AG', 'Antigua y Barbuda, Islas'),
('AI', 'Anguilla, isla'),
('AL', 'Albania'),
('AM', 'Armenia'),
('AN', 'Antillas Holandesas, islas'),
('AO', 'Angola'),
('AQ', 'Antartida'),
('AR', 'Argentina'),
('AS', 'Samoa americana, isla'),
('AT', 'Austria'),
('AU', 'Australia'),
('AW', 'Aruba, isla'),
('AZ', 'Azerbayan'),
('BA', 'Bosnia y Hercegovina'),
('BB', 'Barbados, islas'),
('BD', 'Bangla Desh'),
('BE', 'Belgica'),
('BF', 'Burkina Faso'),
('BG', 'Bulgaria'),
('BH', 'Bahrein'),
('BI', 'Burundi'),
('BJ', 'Benin'),
('BM', 'Bermudas, islas'),
('BN', 'Brunei, sultanato'),
('BO', 'Bolivia'),
('BR', 'Brazil'),
('BS', 'Bahamas, islas'),
('BT', 'Butan'),
('BV', 'Bouvet, isla'),
('BW', 'Botsuana'),
('BY', 'Bielorrusia'),
('BZ', 'Belice'),
('CA', 'Canada'),
('CC', 'Cocos, isla (Keeling)'),
('CD', 'Congo, Republica popular'),
('CF', 'Centroafricana, Republica'),
('CG', 'Congo, Republica'),
('CH', 'Suiza'),
('CI', 'Costa de Marfil'),
('CK', 'Cook, Islas'),
('CL', 'Chile'),
('CM', 'Camerun'),
('CN', 'China'),
('CO', 'Colombia'),
('CR', 'Costa Rica'),
('CU', 'Cuba, isla'),
('CV', 'Cabo Verde, islas'),
('CX', 'Christmas, Islas'),
('CY', 'Chipre, isla'),
('CZ', 'Checa, Republica'),
('DE', 'Alemania'),
('DJ', 'Djibouti'),
('DK', 'Dinamarca'),
('DM', 'Dominica, isla'),
('DO', 'Dominicana, Republica'),
('DZ', 'Argelia'),
('EC', 'Ecuador'),
('EE', 'Estonia'),
('EG', 'Egipto'),
('EH', 'Sahara Occidental'),
('ER', 'Eritrea'),
('ES', 'España'),
('ET', 'Etiopia'),
('FI', 'Finlandia'),
('FJ', 'Fiyi, islas'),
('FK', 'Malvinas, islas'),
('FM', 'Micronesia, islas'),
('FO', 'Faroe, islas'),
('FR', 'Francia'),
('GA', 'Gabon'),
('GB', 'Reino Unido'),
('GD', 'Granada, islas'),
('GE', 'Georgia'),
('GF', 'Guayana francesa'),
('GH', 'Ghana'),
('GI', 'Gibraltar, Peñon'),
('GL', 'Groenlandia'),
('GM', 'Gambia'),
('GN', 'Guinea'),
('GP', 'Guadelupe, islas (Fr.)'),
('GQ', 'Guinea Ecuatorial'),
('GR', 'Grecia'),
('GS', 'Sandwich del sur, islas'),
('GT', 'Guatemala'),
('GU', 'Guam, isla'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HK', 'Hong Kong, China'),
('HM', 'Heard y McDonald, islas'),
('HN', 'Honduras'),
('HR', 'Croacia'),
('HT', 'Haiti'),
('HU', 'Hungria'),
('ID', 'Indonesia'),
('IE', 'Irlanda'),
('IL', 'Israel'),
('IN', 'India'),
('IO', 'Islas del R.U. en el indic'),
('IQ', 'Iraq'),
('IR', 'Iran'),
('IS', 'Islandia'),
('IT', 'Italia'),
('JM', 'Jamaica, isla'),
('JO', 'Jordania'),
('JP', 'Japon'),
('KE', 'Kenia'),
('KG', 'Kirguizistan'),
('KH', 'Camboya'),
('KI', 'Kiribati, islas'),
('KM', 'Comores, islas'),
('KN', 'Saint Kitts y Nevis, islas'),
('KP', 'Korea del Norte'),
('KR', 'Korea del Sur'),
('KW', 'Kuwait'),
('KY', 'Caiman, islas'),
('KZ', 'Kazajstan'),
('LA', 'Laos, Republica'),
('LB', 'Libano'),
('LC', 'Santa Lucia, islas'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Liberia'),
('LS', 'Lesotho'),
('LT', 'Lituania'),
('LU', 'Luxemburgo'),
('LV', 'Letonia'),
('LY', 'Libia'),
('MA', 'Marruecos'),
('MC', 'Monaco'),
('MD', 'Moldavia'),
('MG', 'Madagascar'),
('MH', 'Marshall, Islas'),
('MK', 'Macedonia'),
('ML', 'Mali'),
('MM', 'Myanmar (ex Birmania)'),
('MN', 'Mongolia'),
('MO', 'Macao, isla'),
('MP', 'Marianas, islas del norte'),
('MQ', 'Martinica, islas'),
('MR', 'Mauritania'),
('MS', 'Montserrat, isla'),
('MT', 'Malta, isla'),
('MU', 'Mauricio, islas'),
('MV', 'Maldivas, islas'),
('MW', 'Malawi'),
('MX', 'M�xico'),
('MY', 'Malasia'),
('MZ', 'Mozambique'),
('NA', 'Namibia'),
('NC', 'Nueva Caledonia, isla'),
('NE', 'Niger'),
('NF', 'Norfolk, isla'),
('NG', 'Nigeria'),
('NI', 'Nicaragua'),
('NL', 'Paises Bajos (Holanda)'),
('NO', 'Noruega'),
('NP', 'Nepal'),
('NR', 'Nauru, isla'),
('NU', 'Niue, islas'),
('NZ', 'Nueva Zelandia'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Perú'),
('PF', 'Polinesia francesa'),
('PG', 'Papua Nueva Guinea'),
('PH', 'Filipinas'),
('PK', 'Pakistan'),
('PL', 'Polonia'),
('PM', 'Pierre y Miquelon, islas'),
('PN', 'Pitcairn, islas'),
('PR', 'Puerto Rico'),
('PS', 'Palestina, territorios'),
('PT', 'Portugal'),
('PW', 'Palau, islas'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Reunion, islas'),
('RO', 'Rumania'),
('RU', 'Rusia, federacion'),
('RW', 'Ruanda'),
('SA', 'Arabia Saudi'),
('SB', 'Salomon, islas'),
('SC', 'Seychelles, islas'),
('SD', 'Sudan'),
('SE', 'Suecia'),
('SG', 'Singapur'),
('SH', 'Santa Helena, isla'),
('SI', 'Eslovenia'),
('SJ', 'Svalbard y Jan Mayen, isla'),
('SK', 'Eslovaquia'),
('SL', 'Sierra Leona'),
('SM', 'San Marino'),
('SN', 'Senegal'),
('SO', 'Somalia'),
('SR', 'Surinam'),
('ST', 'Sao Tome y Principe, islas'),
('SV', 'El Salvador'),
('SY', 'Siria'),
('SZ', 'Swazilandia'),
('TC', 'Turks y Ciacos, islas'),
('TD', 'Chad'),
('TF', 'Territorios de Francia en'),
('TG', 'Togo'),
('TH', 'Tailandia'),
('TJ', 'Tajikistan'),
('TK', 'Tokelau, islas'),
('TM', 'Turkmenistan'),
('TN', 'Tunez (Tunicia)'),
('TO', 'Tonga, islas'),
('TP', 'Timor del este'),
('TR', 'Turquia'),
('TT', 'Trinidad y Tobago'),
('TV', 'Tuvalu, islas'),
('TW', 'Taiwan, China'),
('TZ', 'Tanzania'),
('UA', 'Ucrania'),
('UG', 'Uganda'),
('UM', 'Islas menores de USA'),
('US', 'Estados Unidos'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VA', 'Vaticano, ciudad estado'),
('VC', 'San Vincente y Granadinas'),
('VE', 'Venezuela'),
('VG', 'Virgines, Islas (British)'),
('VI', 'Virgines, Islands (USA)'),
('VN', 'Vietnam'),
('VU', 'Vanuatu, islas'),
('WF', 'Wallis y Futuna, islas'),
('WS', 'Samoa Occidental, isla'),
('YE', 'Yemen'),
('YT', 'Mayotte, isla'),
('YU', 'Yugoslavia'),
('ZA', 'Sudafrica'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');

ALTER TABLE usuario
  ADD FOREIGN KEY (codpais) REFERENCES paises (codpais) ON DELETE CASCADE ON UPDATE CASCADE;